// AUTH TYPES 
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGGED_OUT = 'LOGGED_OUT'
export const LOGGED_OUT_FAIL = 'LOGGED_OUT_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

// UI TYPES 
export const EXTEND_MENU = 'EXTEND_MENU'
export const OPEN_BURGER_MENU = 'OPEN_BURGER_MENU'
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'

// DOCUMENTS TYPES 
export const UPLOAD_FAIL = 'UPLOAD_FAIL'
export const ADD_DOCUMENT_SUCCESS = 'ADD_DOCUMENT_SUCCESS'
export const ADD_DOCUMENT_FAIL = 'ADD_DOCUMENT_FAIL'
export const DELETED_ALL = 'DELETED_ALL'
